// Auto-generated from rosy.pest by build.rs — do not edit!
// Regenerate with: cargo build -p rosy-compiler

/// @ts-nocheck
module.exports = grammar({
  name: 'rosy',

  extras: $ => [/\s/, $.comment],

  word: $ => $.identifier,

  rules: {
    source_file: $ => repeat($._item),

    _item: $ => choice(
      $._keyword,
      $._builtin,
      $._type_name,
      $._boolean,
      $.number,
      $.string,
      $.operator,
      $.punctuation,
      $.identifier,
    ),

    comment: $ => seq('{', repeat(choice($.comment, /[^{}]+/)), '}'),

    _keyword: _ => choice(
      'AND', 'and',
      'ARGGET', 'argget',
      'BACKF', 'backf',
      'BEGIN', 'begin',
      'BREAK', 'break',
      'CDF2', 'cdf2',
      'CDFLO', 'cdflo',
      'CDNF', 'cdnf',
      'CDNFDA', 'cdnfda',
      'CDNFDS', 'cdnfds',
      'CLOSEF', 'closef',
      'CPOLVAL', 'cpolval',
      'CPUSEC', 'cpusec',
      'DACLIW', 'dacliw',
      'DACODE', 'dacode',
      'DACQLC', 'dacqlc',
      'DADER', 'dader',
      'DADIU', 'dadiu',
      'DADMU', 'dadmu',
      'DAEPS', 'daeps',
      'DAEPSM', 'daepsm',
      'DAEST', 'daest',
      'DAFILT', 'dafilt',
      'DAFLO', 'daflo',
      'DAFSET', 'dafset',
      'DAGMD', 'dagmd',
      'DAINI', 'daini',
      'DAINT', 'daint',
      'DANORO', 'danoro',
      'DANORS', 'danors',
      'DANOT', 'danot',
      'DANOTW', 'danotw',
      'DANOW', 'danow',
      'DAPEA', 'dapea',
      'DAPEE', 'dapee',
      'DAPEP', 'dapep',
      'DAPEW', 'dapew',
      'DAPLU', 'daplu',
      'DAPRV', 'daprv',
      'DARAN', 'daran',
      'DAREA', 'darea',
      'DAREV', 'darev',
      'DASCL', 'dascl',
      'DASGN', 'dasgn',
      'DATRN', 'datrn',
      'ELSE', 'else',
      'ELSEIF', 'elseif',
      'END', 'end',
      'ENDFIT', 'endfit',
      'ENDFUNCTION', 'endfunction',
      'ENDIF', 'endif',
      'ENDLOOP', 'endloop',
      'ENDPLOOP', 'endploop',
      'ENDPROCEDURE', 'endprocedure',
      'ENDWHILE', 'endwhile',
      'EPSMIN', 'epsmin',
      'FIT', 'fit',
      'FUNCTION', 'function',
      'IF', 'if',
      'IMUNIT', 'imunit',
      'INCLUDE', 'include',
      'INTPOL', 'intpol',
      'LDET', 'ldet',
      'LEV', 'lev',
      'LFALSE', 'lfalse',
      'LINV', 'linv',
      'LOOP', 'loop',
      'LSLINE', 'lsline',
      'LTRUE', 'ltrue',
      'MBLOCK', 'mblock',
      'MEMALL', 'memall',
      'MEMDPV', 'memdpv',
      'MEMFRE', 'memfre',
      'MEMWRT', 'memwrt',
      'MODULE', 'module',
      'MTREE', 'mtree',
      'OPENF', 'openf',
      'OPENFB', 'openfb',
      'OR', 'or',
      'OS', 'os',
      'PLOOP', 'ploop',
      'PNPRO', 'pnpro',
      'POLVAL', 'polval',
      'PROCEDURE', 'procedure',
      'PWTIME', 'pwtime',
      'QUIT', 'quit',
      'READ', 'read',
      'READB', 'readb',
      'READM', 'readm',
      'READS', 'reads',
      'RECST', 'recst',
      'RERAN', 'reran',
      'REWF', 'rewf',
      'RKCO', 'rkco',
      'SAVE', 'save',
      'SCRLEN', 'scrlen',
      'SLEEPM', 'sleepm',
      'STCRE', 'stcre',
      'SUBSTR', 'substr',
      'VARIABLE', 'variable',
      'VEDOT', 'vedot',
      'VELGET', 'velget',
      'VELSET', 'velset',
      'VEUNIT', 'veunit',
      'VEZERO', 'vezero',
      'WHILE', 'while',
      'WRITE', 'write',
      'WRITEB', 'writeb',
      'WRITEM', 'writem'
    ),

    _builtin: _ => choice(
      'ABS', 'abs',
      'ACOS', 'acos',
      'ASIN', 'asin',
      'ATAN', 'atan',
      'CMPLX', 'cmplx',
      'CONJ', 'conj',
      'CONS', 'cons',
      'COS', 'cos',
      'COSH', 'cosh',
      'ERF', 'erf',
      'EXP', 'exp',
      'IMAG', 'imag',
      'INT', 'int',
      'ISRT', 'isrt',
      'ISRT3', 'isrt3',
      'LCD', 'lcd',
      'LCM', 'lcm',
      'LDA', 'lda',
      'LENGTH', 'length',
      'LLO', 'llo',
      'LOG', 'log',
      'LRE', 'lre',
      'LST', 'lst',
      'LTRIM', 'ltrim',
      'LVE', 'lve',
      'NINT', 'nint',
      'NORM', 'norm',
      'POSITION', 'position',
      'REAL', 'real',
      'SIN', 'sin',
      'SINH', 'sinh',
      'SQR', 'sqr',
      'SQRT', 'sqrt',
      'TAN', 'tan',
      'TANH', 'tanh',
      'TRIM', 'trim',
      'TYPE', 'type',
      'VARMEM', 'varmem',
      'VARPOI', 'varpoi',
      'VMAX', 'vmax',
      'VMIN', 'vmin',
      'WERF', 'werf'
    ),

    _type_name: _ => choice(
      'RE', 're',
      'ST', 'st',
      'LO', 'lo',
      'CM', 'cm',
      'VE', 've',
      'DA', 'da',
      'CD', 'cd'
    ),

    _boolean: _ => choice('TRUE', 'true', 'FALSE', 'false'),

    number: _ => /\d+(\.\d+)?/,
    string: _ => choice(/"[^"]*"/, /'(?:''|[^'])*'/),

    operator: _ => choice(
      ':=', '==', '!=', '<>', '<=', '>=',
      '+', '-', '*', '/', '^', '%', '|', '&', '#',
      '=', '<', '>', '!',
    ),

    punctuation: _ => choice(';', '(', ')', '[', ']', ',', '.'),
    identifier: _ => /[a-zA-Z_][a-zA-Z0-9_]*/,
  },
});
