; Auto-generated from rosy.pest by build.rs — do not edit!
; Regenerate with: cargo build -p rosy-compiler

; Comments
(comment) @comment

; Numbers
(number) @number

; Strings
(string) @string

; Operators
(operator) @operator

; Punctuation
(punctuation) @punctuation

; Identifiers (fallback for variables)
(identifier) @variable

; Type names
"RE" @type.builtin
"re" @type.builtin
"ST" @type.builtin
"st" @type.builtin
"LO" @type.builtin
"lo" @type.builtin
"CM" @type.builtin
"cm" @type.builtin
"VE" @type.builtin
"ve" @type.builtin
"DA" @type.builtin
"da" @type.builtin
"CD" @type.builtin
"cd" @type.builtin

; Intrinsic functions
"ABS" @function.builtin
"abs" @function.builtin
"ACOS" @function.builtin
"acos" @function.builtin
"ASIN" @function.builtin
"asin" @function.builtin
"ATAN" @function.builtin
"atan" @function.builtin
"CMPLX" @function.builtin
"cmplx" @function.builtin
"CONJ" @function.builtin
"conj" @function.builtin
"CONS" @function.builtin
"cons" @function.builtin
"COS" @function.builtin
"cos" @function.builtin
"COSH" @function.builtin
"cosh" @function.builtin
"ERF" @function.builtin
"erf" @function.builtin
"EXP" @function.builtin
"exp" @function.builtin
"IMAG" @function.builtin
"imag" @function.builtin
"INT" @function.builtin
"int" @function.builtin
"ISRT" @function.builtin
"isrt" @function.builtin
"ISRT3" @function.builtin
"isrt3" @function.builtin
"LCD" @function.builtin
"lcd" @function.builtin
"LCM" @function.builtin
"lcm" @function.builtin
"LDA" @function.builtin
"lda" @function.builtin
"LENGTH" @function.builtin
"length" @function.builtin
"LLO" @function.builtin
"llo" @function.builtin
"LOG" @function.builtin
"log" @function.builtin
"LRE" @function.builtin
"lre" @function.builtin
"LST" @function.builtin
"lst" @function.builtin
"LTRIM" @function.builtin
"ltrim" @function.builtin
"LVE" @function.builtin
"lve" @function.builtin
"NINT" @function.builtin
"nint" @function.builtin
"NORM" @function.builtin
"norm" @function.builtin
"POSITION" @function.builtin
"position" @function.builtin
"REAL" @function.builtin
"real" @function.builtin
"SIN" @function.builtin
"sin" @function.builtin
"SINH" @function.builtin
"sinh" @function.builtin
"SQR" @function.builtin
"sqr" @function.builtin
"SQRT" @function.builtin
"sqrt" @function.builtin
"TAN" @function.builtin
"tan" @function.builtin
"TANH" @function.builtin
"tanh" @function.builtin
"TRIM" @function.builtin
"trim" @function.builtin
"TYPE" @function.builtin
"type" @function.builtin
"VARMEM" @function.builtin
"varmem" @function.builtin
"VARPOI" @function.builtin
"varpoi" @function.builtin
"VMAX" @function.builtin
"vmax" @function.builtin
"VMIN" @function.builtin
"vmin" @function.builtin
"WERF" @function.builtin
"werf" @function.builtin

; Keywords
"AND" @keyword
"and" @keyword
"ARGGET" @keyword
"argget" @keyword
"BACKF" @keyword
"backf" @keyword
"BEGIN" @keyword
"begin" @keyword
"BREAK" @keyword
"break" @keyword
"CDF2" @keyword
"cdf2" @keyword
"CDFLO" @keyword
"cdflo" @keyword
"CDNF" @keyword
"cdnf" @keyword
"CDNFDA" @keyword
"cdnfda" @keyword
"CDNFDS" @keyword
"cdnfds" @keyword
"CLOSEF" @keyword
"closef" @keyword
"CPOLVAL" @keyword
"cpolval" @keyword
"CPUSEC" @keyword
"cpusec" @keyword
"DACLIW" @keyword
"dacliw" @keyword
"DACODE" @keyword
"dacode" @keyword
"DACQLC" @keyword
"dacqlc" @keyword
"DADER" @keyword
"dader" @keyword
"DADIU" @keyword
"dadiu" @keyword
"DADMU" @keyword
"dadmu" @keyword
"DAEPS" @keyword
"daeps" @keyword
"DAEPSM" @keyword
"daepsm" @keyword
"DAEST" @keyword
"daest" @keyword
"DAFILT" @keyword
"dafilt" @keyword
"DAFLO" @keyword
"daflo" @keyword
"DAFSET" @keyword
"dafset" @keyword
"DAGMD" @keyword
"dagmd" @keyword
"DAINI" @keyword
"daini" @keyword
"DAINT" @keyword
"daint" @keyword
"DANORO" @keyword
"danoro" @keyword
"DANORS" @keyword
"danors" @keyword
"DANOT" @keyword
"danot" @keyword
"DANOTW" @keyword
"danotw" @keyword
"DANOW" @keyword
"danow" @keyword
"DAPEA" @keyword
"dapea" @keyword
"DAPEE" @keyword
"dapee" @keyword
"DAPEP" @keyword
"dapep" @keyword
"DAPEW" @keyword
"dapew" @keyword
"DAPLU" @keyword
"daplu" @keyword
"DAPRV" @keyword
"daprv" @keyword
"DARAN" @keyword
"daran" @keyword
"DAREA" @keyword
"darea" @keyword
"DAREV" @keyword
"darev" @keyword
"DASCL" @keyword
"dascl" @keyword
"DASGN" @keyword
"dasgn" @keyword
"DATRN" @keyword
"datrn" @keyword
"ELSE" @keyword
"else" @keyword
"ELSEIF" @keyword
"elseif" @keyword
"END" @keyword
"end" @keyword
"ENDFIT" @keyword
"endfit" @keyword
"ENDFUNCTION" @keyword
"endfunction" @keyword
"ENDIF" @keyword
"endif" @keyword
"ENDLOOP" @keyword
"endloop" @keyword
"ENDPLOOP" @keyword
"endploop" @keyword
"ENDPROCEDURE" @keyword
"endprocedure" @keyword
"ENDWHILE" @keyword
"endwhile" @keyword
"EPSMIN" @keyword
"epsmin" @keyword
"FIT" @keyword
"fit" @keyword
"FUNCTION" @keyword
"function" @keyword
"IF" @keyword
"if" @keyword
"IMUNIT" @keyword
"imunit" @keyword
"INCLUDE" @keyword
"include" @keyword
"INTPOL" @keyword
"intpol" @keyword
"LDET" @keyword
"ldet" @keyword
"LEV" @keyword
"lev" @keyword
"LFALSE" @keyword
"lfalse" @keyword
"LINV" @keyword
"linv" @keyword
"LOOP" @keyword
"loop" @keyword
"LSLINE" @keyword
"lsline" @keyword
"LTRUE" @keyword
"ltrue" @keyword
"MBLOCK" @keyword
"mblock" @keyword
"MEMALL" @keyword
"memall" @keyword
"MEMDPV" @keyword
"memdpv" @keyword
"MEMFRE" @keyword
"memfre" @keyword
"MEMWRT" @keyword
"memwrt" @keyword
"MODULE" @keyword
"module" @keyword
"MTREE" @keyword
"mtree" @keyword
"OPENF" @keyword
"openf" @keyword
"OPENFB" @keyword
"openfb" @keyword
"OR" @keyword
"or" @keyword
"OS" @keyword
"os" @keyword
"PLOOP" @keyword
"ploop" @keyword
"PNPRO" @keyword
"pnpro" @keyword
"POLVAL" @keyword
"polval" @keyword
"PROCEDURE" @keyword
"procedure" @keyword
"PWTIME" @keyword
"pwtime" @keyword
"QUIT" @keyword
"quit" @keyword
"READ" @keyword
"read" @keyword
"READB" @keyword
"readb" @keyword
"READM" @keyword
"readm" @keyword
"READS" @keyword
"reads" @keyword
"RECST" @keyword
"recst" @keyword
"RERAN" @keyword
"reran" @keyword
"REWF" @keyword
"rewf" @keyword
"RKCO" @keyword
"rkco" @keyword
"SAVE" @keyword
"save" @keyword
"SCRLEN" @keyword
"scrlen" @keyword
"SLEEPM" @keyword
"sleepm" @keyword
"STCRE" @keyword
"stcre" @keyword
"SUBSTR" @keyword
"substr" @keyword
"VARIABLE" @keyword
"variable" @keyword
"VEDOT" @keyword
"vedot" @keyword
"VELGET" @keyword
"velget" @keyword
"VELSET" @keyword
"velset" @keyword
"VEUNIT" @keyword
"veunit" @keyword
"VEZERO" @keyword
"vezero" @keyword
"WHILE" @keyword
"while" @keyword
"WRITE" @keyword
"write" @keyword
"WRITEB" @keyword
"writeb" @keyword
"WRITEM" @keyword
"writem" @keyword

; Booleans
"TRUE" @constant.builtin
"true" @constant.builtin
"FALSE" @constant.builtin
"false" @constant.builtin
